### ISSUE TITLE
Problem with ie 11

### ISSUE THREAD

**Issue by pechischev** [indutny/asn1.js#125]
Hello.
I did catch error on ie 11. Can you fix it? 

```
Syntax error at  ./node_modules/asn1.js/lib/asn1/base/buffer.js:3:1
```
![image](https://user-images.githubusercontent.com/14825339/95747256-cedfb480-0ca0-11eb-856c-afcb008836a6.png)

I used windows 8 and webpack 4.44.2

**Comment by hzc315579049** [comment]
> Hello.
> I did catch error on ie 11. Can you fix it?
> 
> ```
> Syntax error at  ./node_modules/asn1.js/lib/asn1/base/buffer.js:3:1
> ```
> 
> ![image](https://user-images.githubusercontent.com/14825339/95747256-cedfb480-0ca0-11eb-856c-afcb008836a6.png)
> 
> I used windows 8 and webpack 4.44.2

>it need to be complie when your babel-loader dosent complie ./node_module.this module export with es6 syntax.
